config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :post_saunas, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    get "tagsearches/search" => "tagsearches#search"
    get "searches/search" => "searches#search"
    patch "admin/users/information/:id" => "users#update", as: 'users_information_update'
    resources :users, only: [:index, :show, :edit] do
      member do
        get :liked_post_saunas
      end
      get "followings" => "relationships#followings", as: 'followings'
      get "followers" => "relationships#followers", as: 'followers'
    end
  end


  # 顧客側のルーティング設定
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: 'public' do
    root to: "homes#top"
    get "about" => "homes#about"
    patch "post_saunas/:id" => "post_saunas#update", as: 'post_saunas_update'
    resources :post_saunas, only: [:index, :create, :new, :edit, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "tagsearches/search" => "tagsearches#search"
    get "searches/search" => "searches#search"
    get "users/information/edit/:id" => "users#edit", as: 'users_information_edit'
    patch "users/information/:id" => "users#update", as: 'users_information_update'
    resources :users, only: [:index, :show] do
      member do
        get :liked_post_saunas
      end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: 'followings'
        get "followers" => "relationships#followers", as: 'followers'
    end
  end

  # ゲストユーザーのルーティング設定
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_sauna.rb
class PostSauna < ApplicationRecord
  # サウナ画像
  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  #リレーション
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 絞り込み機能
  def self.search(search, word)
    if search == "perfect_match"
      @post_sauna = PostSauna.where(name: "#{word}")
    elsif search == "partial_match"
      @post_sauna = PostSauna.where("name LIKE?", "%#{word}%")
    else
      @post_sauna = PostSauna.all
    end
  end

  # いいねをつけた投稿の取得
  def self.liked_post_saunas(user)           # 1. モデル内での操作を開始
    includes(:favorites)                           # 2. post_favorites テーブルを結合
      .where(favorites: {user_id: user.id})        # 3. ユーザーがいいねしたレコードを絞り込み
      .order(created_at: :desc)                    # 4. 投稿を作成日時の降順でソート
  end

  #バリデーション
  validates :image, presence: true
  validates :name, length: { in: 1..50 }
  validates :address, length: { in: 1..100 }
  validates :price, length: { in: 1..10 }, numericality: true
  validates :impression, length: { in: 1..200 }
  validates :category, length: { in: 1..50 }
end

app/controllers/admin/post_saunas_controller.rb
class Admin::PostSaunasController < ApplicationController

  #権限設定
  before_action :authenticate_admin!

  def index
    @post_saunas = PostSauna.page(params[:page])
  end

  def show
    @post_sauna = PostSauna.find(params[:id])
    @user = @post_sauna.user
  end

  def destroy
    post_sauna = PostSauna.find(params[:id])
    post_sauna.destroy
    flash[:notice] = "削除に成功しました。"
    redirect_to admin_post_saunas_path
  end

end

app/helpers/admin/post_saunas_helper.rb
module Admin::PostSaunasHelper
end

app/views/admin/post_saunas/_post_sauna.index.html.erb
<div class="d-flex flex-wrap">
  <% post_saunas.each do |post_sauna| %>
    <div class="card m-4 text-center" style="width: 23rem;">
      <%= image_tag post_sauna.get_image, height: "300px",class:"rounded" %>
      <div class="card-body">
        <h5 class="card-title"><%= link_to post_sauna.name, admin_post_sauna_path(post_sauna)%></h5>
        <p class="card-text">感想：<%= post_sauna.impression %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">所在地：<%= post_sauna.address %></li>
        <li class="list-group-item">利用料金：<%= post_sauna.price %>円</li>
        <li class="list-group-item">カテゴリー：<%=link_to post_sauna.category,admin_tagsearches_search_path(content: post_sauna.category)%></li>
        <li class="list-group-item">評価 : <%= render "public/post_saunas/static.rate", post_sauna: post_sauna %></li>
      </ul>
      <div class="card-body">
        <div>投稿ユーザー画像：<%= image_tag post_sauna.user.get_profile_image(100,100), class: "mt-3 rounded"; %></div>
        <p>ユーザーネーム：<%= link_to post_sauna.user.name, admin_user_path(post_sauna.user.id) %></p>
        <span><%= link_to "コメント数：#{post_sauna.post_comments.count}", admin_post_sauna_path(post_sauna.id) %></span>
      </div>
    </div>
  <% end %>
</div>
<%= paginate post_saunas %>

app/views/admin/post_saunas/index.html.erb
<div class="col-md-9 offset-md-2 mt-3 mb-3">
  <div class="row">
    <div class="col">
      <h4 class="mb-3"><i class="fa-solid fa-fire-flame-curved"></i> サウナ一覧</h4>
      <% if @post_saunas.exists? %>
        <%= render "post_sauna.index", post_saunas: @post_saunas %>
      <% else %>
        <p>※投稿はまだありません<p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/post_saunas/show.html.erb
<div class="containar mt-3 mb-3">
  <div class="row">
    <div class="col-md-3 offset-md-1">
      <%= render 'admin/users/info', user: @user %>
    </div>
    <div class="col-md-3">
      <h4 class="mb-3"><i class="fa-solid fa-fire-flame-curved"></i> サウナ詳細</h4>
      <div class="card" style="width: 25rem;">
        <%= image_tag @post_sauna.get_image,class:"rounded" %>
        <div class="card-body">
          <h5 class="card-title"><%= @post_sauna.name %></h5>
          <p class="card-text">感想：<%= @post_sauna.impression %></p>
          <p class="card-text">投稿日：<%= @post_sauna.created_at.strftime('%Y/%m/%d') %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">所在地：<%= @post_sauna.address %></li>
          <li class="list-group-item">利用料金：<%= @post_sauna.price %>円</li>
          <li class="list-group-item">カテゴリー：<%= link_to @post_sauna.category, admin_tagsearches_search_path(content:@post_sauna.category)%></li>
          <li class="list-group-item">評価：<%= render "public/post_saunas/static.rate", post_sauna: @post_sauna %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <div class="d-flex">
          <p class="px-2">
            <i class="fa-solid fa-heart text-danger">
              <%= @post_sauna.favorites.count %> いいね
            </i>
          </p>
          <p class="px-2">コメント数：<%= @post_sauna.post_comments.count %></p>
        </div>
        <% @post_sauna.post_comments.each do |post_comment| %>
          <div class="d-flex mt-5">
            <div class="pe-3">
              <%= image_tag post_comment.user.get_profile_image(100,100),class:"rounded" %>
              <p><%= link_to post_comment.user.name, admin_user_path(post_comment.user.id) %></p>
            </div>
            <div class="pt-4 px-3">
              <p><%= post_comment.comment %></p>
              <p>コメント日時：<%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
            </div>
          </div>
          <div>
            <%= link_to "コメント削除", admin_post_sauna_post_comment_path(post_comment.post_sauna, post_comment), method: :delete, data: {confirm: "コメントを削除しますか？"}, class:"btn btn-danger btn-sm" %>
          </div>
        <% end %>
        <div class="text-right pt-3">
          <p class="mx-3"><%= link_to "投稿削除", admin_post_sauna_path(@post_sauna), method: :delete, data: {confirm: "投稿を削除しますか？"}, class:"btn btn-outline-danger" %></p>
        </div>
      </div>
    </div>
  </div>
</div>