config/routes.rb
Rails.application.routes.draw do
  # 管理者側のルーティング設定
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :post_saunas, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    get "tagsearches/search" => "tagsearches#search"
    get "searches/search" => "searches#search"
    patch "admin/users/information/:id" => "users#update", as: 'users_information_update'
    resources :users, only: [:index, :show, :edit] do
      member do
        get :liked_post_saunas
      end
      get "followings" => "relationships#followings", as: 'followings'
      get "followers" => "relationships#followers", as: 'followers'
    end
  end


  # 顧客側のルーティング設定
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: 'public' do
    root to: "homes#top"
    get "about" => "homes#about"
    patch "post_saunas/:id" => "post_saunas#update", as: 'post_saunas_update'
    resources :post_saunas, only: [:index, :create, :new, :edit, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "tagsearches/search" => "tagsearches#search"
    get "searches/search" => "searches#search"
    get "users/information/edit/:id" => "users#edit", as: 'users_information_edit'
    patch "users/information/:id" => "users#update", as: 'users_information_update'
    resources :users, only: [:index, :show] do
      member do
        get :liked_post_saunas
      end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: 'followings'
        get "followers" => "relationships#followers", as: 'followers'
    end
  end

  # ゲストユーザーのルーティング設定
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #プロフィール画像
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #ドリンク画像
  has_one_attached :favorite_drink_image

  def get_favorite_drink_image(width, height)
    unless favorite_drink_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      favorite_drink_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    favorite_drink_image.variant(resize_to_limit: [width, height]).processed
  end


  #リレーション
  has_many :post_saunas, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  # フォローしている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  # フォローされている関連付け
  has_many :followings, through: :active_relationships, source: :followed # フォローしているユーザーを取得
  has_many :followers, through: :passive_relationships, source: :follower # フォロワーを取得

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end

  # 絞り込み機能
  def self.search(search, word)
    if search == "perfect_match"
      @user = User.where(name: "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  #ゲストユーザーメソッド
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.introduction = "guestuser_introduction"
      user.favorite_drink = "guestuser_favorite_drink"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  #ユーザーステータス管理
  def user_status
    if is_active == true
      "有効"
    else
      "利用停止"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

  #バリデーション
  validates :name,  length: { in: 1..50 }
  validates :introduction, length: { in: 1..100 }
  validates :favorite_drink, length: { in: 1..50 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  #権限設定
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @post_saunas = @user.post_saunas.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "編集に成功しました。"
        redirect_to admin_user_path(@user)
      else
        flash.now[:alert] = "編集に失敗しました。"
        render :edit
      end
  end

  def liked_post_saunas
    @user = User.find(params[:id])
    @liked_post_saunas = PostSauna.liked_post_saunas(@user).page(params[:page])
  end


  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction, :favorite_drink_image, :favorite_drink, :is_active)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_info.html.erb
<h4 class="ml-3"><i class="fa-solid fa-fire-flame-curved"></i> 会員情報</h4>
<div class="text-center mb-2">
  <i class="fa-solid fa-user"></i> <%= image_tag user.get_profile_image(100,100) ,class:"mr-4 rounded" %>
  <i class="fa-solid fa-bottle-droplet"></i> <%= image_tag user.get_favorite_drink_image(100,100),class:"rounded" %>
</div>

<table class="table">
  <tr>
    <td noWrap>ユーザーネーム</td>
    <td><%= link_to user.name, admin_user_path(user) %></td>
  </tr>
  <tr>
    <td>自己紹介</td>
    <td><%= user.introduction %></td>
    </tr>
  <tr>
    <td>お気に入り<br>ドリンク</td>
    <td><%= user.favorite_drink %></td>
  </tr>
  <tr>
    <td>フォロー数</td>
    <td><%= link_to user.followings.count, admin_user_followings_path(user) %></td>
  </tr>
  <tr>
    <td>フォロワー数</td>
    <td><%= link_to user.followers.count, admin_user_followers_path(user) %></td>
  </tr>
  <tr>
    <td>ステータス</td>
    <td>
      <% if user.is_active %>
        <span class="badge badge-success">有効</span>
      <% else %>
        <span class="badge badge-danger">利用停止</span>
      <% end %>
    </td>
  </tr>
</table>
<div class="row d-flex justify-content-center">
    <%= link_to "ユーザー情報編集", edit_admin_user_path(user), class:"btn info w-50 my-2 mx-5" %>
    <%= link_to "いいね一覧", liked_post_saunas_admin_user_path(user), class:"btn info w-50 my-2 mx-5" %>
</div>

app/views/admin/users/_user.index.html.erb
<table class="table">
  <thead>
    <tr noWrap>
      <th>会員ID</th>
      <th>ユーザーネーム</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <% users.each do |user| %>
    <tbody>
      <tr noWrap>
        <td><%= user.id %></td>
        <td><%= link_to user.name, admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.is_active %>
            <span class="badge badge-primary">有効</span>
          <% else %>
            <span class="badge badge-danger">利用停止</span>
          <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>
<%= paginate users %>

app/views/admin/users/edit.html.erb
<div class="container mt-4 mb-3">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <%= pluralize(@user.errors.count, "エラー") %>が発生しました
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="card text-center">
        <div class="card-header">
          <h2>ユーザー情報編集</h2>
        </div>
        <%= form_with model: @user, url: admin_users_information_update_path(@user), html: { multipart: true } do |f| %>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <label>会員ID</label><br>
                <%= @user.id %>
              </li>
              <li class="list-group-item">
                <label for="inputImage">プロフィール画像</label><br>
                <%= f.file_field :profile_image, class: "form-control", accept: "image/*" %>
              </li>
              <li class="list-group-item">
                <label for="inputName">ユーザーネーム</label><br>
                <%= f.text_field :name, autofocus: true, class: "form-control", id: "inputName", placeholder: "名前" %>
              </li>
              <li class="list-group-item">
                <label for="inputIntroduction">自己紹介</label><br>
                <%= f.text_area :introduction, class: "form-control", id: "inputIntroduction", placeholder: "自己紹介" %>
              </li>
              <li class="list-group-item">
                <label for="inputImage">ドリンク画像</label><br>
                <%= f.file_field :favorite_drink_image, class: "form-control", accept: "image/*" %>
              </li>
              <li class="list-group-item">
                <label for="inputFavoriteDrink">お気に入りのドリンク</label><br>
                <%= f.text_field :favorite_drink, autofocus: true, class: "form-control", id: "inputFavoriteDrink", placeholder: "お気に入りの飲み物" %>
              </li>
              <li class="list-group-item">
                <label>ステータス</label><br>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :is_active, true, id: "is_active_true", class: "form-check-input" %>
                  <%= label_tag "is_active_true", "有効", class: "form-check-label" %>
                </div>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :is_active, false, id: "is_active_false", class: "form-check-input" %>
                  <%= label_tag "is_active_false", "利用停止", class: "form-check-label" %>
                </div>
              </li>
            </ul>
            <%= f.submit "更新する", class: "btn submit mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <div class="row">
    <div class="col">
      <h4 class="mb-3"><i class="fa-solid fa-fire-flame-curved"></i> 会員一覧</h4>
      <% if @users.exists? %>
        <%= render 'user.index', users: @users %>
      <% else %>
        <p>※ユーザーはまだ登録されていません<p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/liked_post_saunas.html.erb
<div class="containar mt-3 mb-3">
  <div class="row">
    <div class="col-md-3 offset-md-1 mt-3">
      <%= render 'info', user: @user %>
    </div>
    <div class="col-md-8">
      <h2>"<%= @user.name %>"いいね投稿一覧</h2>
        <% if @liked_post_saunas.exists? %>
          <%= render "admin/post_saunas/post_sauna.index", post_saunas: @liked_post_saunas %>
        <% else %>
          <p>※ユーザーがいいねした投稿はまだありません<p>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="containar mt-3">
  <div class="row">
    <div class="col-md-3 offset-md-1">
      <%= render 'info', user: @user %>
    </div>
    <div class="col-md-8">
      <h4><i class="fa-solid fa-fire-flame-curved"></i> <%= @user.name %>のサウナ一覧</h4>
      <div class="d-flex flex-wrap">
        <% if @post_saunas.exists? %>
          <% @post_saunas.each do |post_sauna| %>
            <div class="card m-3" style="width: 19rem;">
              <%= image_tag post_sauna.get_image,class:"rounded" %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to post_sauna.name, admin_post_sauna_path(post_sauna)%></h5>
                <p class="card-text">感想：<%= post_sauna.impression %></p>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">所在地：<%= post_sauna.address %></li>
                <li class="list-group-item">利用料金：<%= post_sauna.price %>円</li>
                <li class="list-group-item">カテゴリー：<%=link_to post_sauna.category, admin_tagsearches_search_path(content: post_sauna.category)%></li>
                <li class="list-group-item">評価：<%= render "public/post_saunas/static.rate", post_sauna: post_sauna %></li>
              </ul>
              <div class="card-body">
                <span><%= link_to "コメント数：#{post_sauna.post_comments.count}", admin_post_sauna_path(post_sauna.id) %></span>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>※投稿はまだありません<p>
        <% end %>
      </div>
      <%= paginate @post_saunas %>
    </div>
  </div>
</div>